const htmlAnchor = $('<a target="_blank">');
const htmlBody = $('body');
const htmlBreak = $('<br/>');
const htmlButton = $('<button></button>');
const htmlDiv = $('<div></div>');
const htmlFooter = $('<footer></footer>');
const htmlHeader = $('<header></header>');
const htmlImg = $('<img />');
const htmlInputFile = $('<input type="file" name="files[]" multiple />');
const htmlInputText = $('<input type="text" />');
const htmlParagraph = $('<p></p>');
const htmlSection = $('<section></section>');
const htmlSpan = $('<span></span>');